name: MergeToDevelop

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  createPullRequest:
   
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Pull Request Action
    # You may pin to the exact commit or the version.
    # uses: repo-sync/pull-request@ea6773388b83b337e4da9a223293309f2c3670e7
      uses: repo-sync/pull-request@v2.3
      with:
        # Branch name to pull from, default is triggered branch
        source_branch: nuu
        # Branch name to sync to in this repo, default is master
        destination_branch: dev
        # Pull request title
        pr_title: 'integracion'
        # Pull request body
        pr_body: 'autogenerada'
        pr_reviewer: 'AoSc920411'
        pr_assignee: 'AoSc920411'
        # GitHub token secret
        github_token: 'db1e22145e3cb51aa0641106b74d5211acbb9c27'
