name: Swift

on:
  create:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test File
      run: git status | head -n1 >> infoBranch.txt; git add .; git commit -m 'InfoGit';
